services:
  api:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/eventx
      - JWT_SECRET=${JWT_SECRET:-devsecret}
      - QR_SECRET=${QR_SECRET:-devqrsecret}
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
